openapi: '3.0.3'
info:
  title: WASAphoto's APIs
  description: |-
    The following APIs are for Wasa's first Homework
  version: "1"

  

paths:
  /login:
    post:
      tags:  ["login"] 
      summary: Logs in the user
      description: |
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: Maria
                  pattern: '^[a-zA-Z0-9]+$'
                  minLength: 3
                  maxLength: 16
                password:
                  type: string
                  example: paperino05
                  pattern: '^.*?$'
                  minLength: 8
                  maxLength: 25
  
        required: true
      responses:
        '201': 
          description: User log-in action successfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string 
                    example: "abcdefgg45"





 
      
        
            
            
    

      
      










  
  
        

              
   

      



  
    

